trigger:
- main
pool:
 vmImage: ubuntu-latest
stages:
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: echo testing-app
- stage: dev
  jobs:
  - job: deploytodev
    steps:
    - script: echo deploying to the dev env
- stage: Blue
  jobs:
  - job: deploytoblue
    steps:
    - script: echo deploy to blue env
- stage: production
  jobs:
  - job: deploytoprod
    steps:
    - script: echo deploying to production